version: "3.8"
services:
  # web:
  #   build: ./client/
  #   ports:
  #     - "5005:80"
  #   depends_on:
  #     - postgres
  #   environment:
  #     - APP_API_URL=http://localhost:5000 # Set the API URL
  # flask:
  #   build: ./server/
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - postgres
  postgres:
    image: postgres:16.2-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql # Mount the init.sql file
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password