version: "3.8"
services:
  web:
    build: ./client/
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - APP_API_URL=http://flask:5000 # Set the API URL
  flask:
    build: ./server/
    depends_on:
      - db
  db:
    image: postgres:16.2-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql # Mount the init.sql file
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password